@startuml
title Context Diagram C4_Context_MVP

skinparam defaultTextAlignment center
skinparam PackageStyle rect
skinparam ArrowThickness 1

top to bottom direction
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(patient, "Patient", "Record management, view analysis")
Person(reception, "Reception", "Manages appointments")
Person(doctor, "Doctor", "Accesses medical records")
Person(bookkeeper, "Bookkeeper", "Handles accounting")
Person(warehouse, "Warehouse keeper", "Manages inventory")

System_Ext(lab, "External Laboratory", "Provides lab results via API")
System_Ext(payment_provider, "Payment Gateway", "Processes payments")

System_Boundary(system, "Platform To-Be") {

    System_Boundary(layer1, "Business Services") {
        System(portal, "Patient Portal", "Self-service booking and personal data access")
        System(reception_portal, "Reception Portal", "Appointment management")

        System(crm, "CRM Core", "Single source of truth for patient data")
        System(billing, "Billing Service", "Handles payments and financial records")
        System(lab_service, "Lab Integration Service", "Secure lab API integration")
    }


    System_Boundary(layer2, "Security & Governance") {
       System(iam, "IAM / Keycloak", "Authentication & Authorization")
        System(audit, "Audit & Logging Service", "Access tracking")
        System(data_catalog, "Data Catalog / Tag Engine", "Tagging & classification")
        System(dlp, "DLP Engine", "Sensitive data scanning")

    }

    System_Boundary(layer3, "Analytics") {
        System(data_lake, "Data Lake", "Raw & processed data storage")
        System(analytics, "Analytics Platform", "BI / ML / AI workloads")
        System(siem, "SIEM", "Security monitoring")
    }
}

Rel(patient, portal, "Uses")
Rel(reception, reception_portal, "Uses")
Rel(doctor, crm, "Accesses records")
Rel(bookkeeper, billing, "Uses")
Rel(warehouse, billing, "Inventory sync")

Rel(portal, iam, "Authenticate")
Rel(reception_portal, iam, "Authenticate")
Rel(crm, iam, "RBAC/ABAC")
Rel(crm, audit, "Logs access")
Rel(crm, data_catalog, "Tag check")
Rel(lab_service, lab, "Secure API (TLS + OAuth2)")
Rel(billing, payment_provider, "Secure API")
Rel(crm, data_lake, "Event-based export")
Rel(data_lake, analytics, "Controlled access")
Rel(analytics, data_catalog, "Tag-aware access")
Rel(data_lake, dlp, "Scan sensitive data")
Rel(audit, siem, "Security events")


@enduml